name: MacOS build
on:
  release:
    types:
      - released

jobs:
  release:
    name: MacOS build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install tesseract and leptonica
        run: |
          brew install tesseract leptonica
      - name: Build
        run: |
          PATH="/usr/local/opt/llvm/bin:$PATH" BINDGEN_EXTRA_CLANG_ARGS='-I"/usr/local/Cellar/tesseract/5.0.1/include" -I"/usr/local/Cellar/leptonica/1.82.0/include"' cargo build --release
      - name: Move and Zip
        run: | 
          mv target/release/noname noname
          tar -czf noname-macos.tar.gz noname
      - name: SHA256
        run: |
          shasum -a 256 noname-macos.tar.gz
      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
            -f \
            -sSL \
            -XPOST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Length: $(stat -f%z noname-macos.tar.gz)" \
            -H "Content-Type: application/octet-stream" \
            --upload-file "noname-macos.tar.gz" \
            "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets?name=noname-macos.tar.gz"