name: Test
on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Check Clang Version
        run: |
          clang --version
      - name: Switch to llvm clang
        run: |
          echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> /Users/runner/.bash_profile
          export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
          export CPPFLAGS="-I/usr/local/opt/llvm/include"
          source /Users/runner/.bash_profile
          sudo xcode-select -r
      - name: Check Clang Version
        run: |
          clang --version

