name: Test
on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Test
    runs-on: macos-10.15
    steps:
      - name: Check CLang Version
        run: |
          clang --version
      - name: Install llvm
        run: |
          brew install llvm
      - name: Check CLang Version
        run: |
          clang --version

